### ISSUE TITLE
[BUG] Gallery example display issue when back from detail view to list view

### ISSUE THREAD

**Issue by ghostfox911** [renancaraujo/photo_view#190] opened 2019-10-16 03:16 UTC
**Describe the bug**
Gallery example display issue when back from detail view to list view.

**Environment**
- flutter_windows_v1.9.1+hotfix.4-stable
- photo_view 0.5.0

**To Reproduce**
- Run the example provided here: photo_view/example/lib/screens/examples/gallery/gallery_example.dart
- In the main view tap on the 6th item 'Gallery'.
- In the 'Gallery Example' view tap on the photo on the right of the list.
- In the detail view, slide from left to right to view the photo next to it.
- Tap the back button to trigger the Navigation.pop.
- Two photos played hero animations or the right one disappeared and left a blank on the right.

**What is the current behavior?**
Two photos played hero animations or the right one disappeared and left a blank on the right.

**Expected behavior**
Only the one in the detail view plays hero animation and no other photos disappeared in the list when back button is tapped.

**Screenshots**
NA

**Is this a *feature* or report a *bug*?**
Bug report.

**Comment by renancaraujo** [comment] 2019-10-16 08:43
Dupe of #178

**Closed by renancaraujo** 2019-10-16 08:43 UTC
Labels: bug
