### ISSUE TITLE
[BUG]Gallery Example thumbnail disappear when switch PhotoViewGallery pop back

### ISSUE THREAD

**Issue by RemmoYu** [renancaraujo/photo_view#178] opened 2019-09-05 09:30 UTC
**Describe the bug**
Gallery Example thumbnail disappear when switch PhotoViewGallery and pop back

**To Reproduce**
1. Run Gallery Example with android emulator,
2. Tap the thumbnail to open GalleryPhotoViewWrapper,
3. Swich to next photo,
4. Click the back button, the thumbnail disappeared!

➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.8-pre.82, on Mac OS X 10.15 19A546d, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.0)
[✓] Connected device (2 available)

• No issues found!
➜  ~ 

![91i7k-ion2y](https://user-images.githubusercontent.com/8110686/64329995-c2e7e480-d002-11e9-9cef-8f1a3483af66.gif)

**Comment by renancaraujo** [comment] 2019-09-07 13:06
Can you confirm it still happens with flutter 1.7?

Tried to reproduce, by all means, I couldn't. 

We had a lot of weird issues with images that were fixed on the last updates, like this [one](https://github.com/renancaraujo/photo_view/issues/162). 

For the sake of organization, I will clsoe this issue for now. If you think the problem persists, feel free to reopen it.

**Comment by RemmoYu** [comment] 2019-09-09 01:56
ok，it works ok with flutter stable channel v1.7.8+hotfix.4,  but still happens with flutter master v1.10.1-pre.41.

**Comment by kamaldaniels** [comment] 2019-09-13 08:28
I have seen it in my own app... It seems to be related to the hero widget going off screen. If I removed the heroTag, the image doesn't disappear. Looks to be related to: https://github.com/flutter/flutter/issues/40239

**Comment by dshukertjr** [comment] 2019-09-16 02:21
I have the same bug. I am guessing this caused this bug: https://github.com/flutter/flutter/pull/37341

**Comment by Addictorator** [comment] 2019-10-14 11:24
Can confirm this is caused by [flutter/flutter#37341](https://github.com/flutter/flutter/pull/37341). The earliest version with a fix is v.1.10.14: [`6430012`](https://github.com/flutter/flutter/commit/64300123faa692c1ac3d8feeba171a6e079a741e), which is currently in beta branch. I've upgraded flutter to v.1.10.14 and the issue is fixed, so I would say this is not a problem with a package, but due to a bug in flutter, and consider this issue closed?

**Comment by renancaraujo** [comment] 2019-10-14 11:54
@Addictorator I think so. Thank you for tracking this down. 

So since it is a framework issue with a built-in solution (no workarounds available), there is nothing we can do here. 

If you disagree our think the problem was not really tackled, feel free to answer here and perhaps we can reopen this issue.

**Closed by renancaraujo** 2019-10-14 11:54 UTC
Labels: bug
