### ISSUE TITLE
Can't update to the last version 

### ISSUE THREAD

**Issue by marcuslma** [renancaraujo/photo_view#103] opened 2019-02-20 13:51 UTC
Hello,
I am trying to update the package to it's last version (0.2.0) and I am getting the following error.

```
Running "flutter packages get" in centraldofranqueado-flutter...     
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because app_central depends on photo_view >=0.2.0 which requires SDK version >=2.1.0 <3.0.0, version solving failed.
```

There is something that I need to change in my flutter app?

**Comment by renancaraujo** [comment] 2019-02-20 17:12
Dupe of #94 

Releasing fixes now to 0.2.1.

**Comment by marcuslma** [comment] 2019-02-20 17:13
Thanks! Closing.

**Closed** 2019-02-20 17:13 UTC

**Comment by renancaraujo** [comment] 2019-02-20 17:43
Released
