### ISSUE TITLE
if failed once does not work again[BUG]

### ISSUE THREAD

**Issue by asarkar1990** [renancaraujo/photo_view#272] opened 2020-04-11 11:49 UTC
**Describe the bug**
if for any reason like network issue or invalid url the loading failed and "loadFailedChild" render. Then if I change the imageUrl with a valid url then aslo the image never show up.

**To Reproduce**
Steps to reproduce the behavior.

` NetworkImage(imageUrl),`

setState((){
imageUrl = "invalidurl";
});

setState((){
imageUrl = "valid url";
});

**What is the current behavior?**
Once failed it never load the image

**Expected behavior**
if it failed and then correct url is provided it should render.

**Screenshots**

**Is this a *feature* or report a *bug*?**
it's a bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. **

**What is the expected behavior?**

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**

**Additional context**

**Comment by renancaraujo** [comment] 2020-08-14 08:57
dupe of #275

**Closed by renancaraujo** 2020-08-14 08:57 UTC
Labels: bug
