### ISSUE TITLE
[BUG] method "toDouble" was called on null.

### ISSUE THREAD

**Issue by ericklhe** [renancaraujo/photo_view#222] opened 2019-12-03 21:11 UTC
**Describe the bug**
When resetting the scale of the photoview controller using the initial scale fo the photovie controller, I get the error.

**To Reproduce**
Steps to reproduce the behavior.

### **controller photo view page**
![image](https://user-images.githubusercontent.com/16799511/70089024-c4b74900-15ed-11ea-86a6-522113c105f8.png)

### **build**
![image](https://user-images.githubusercontent.com/16799511/70089073-d7ca1900-15ed-11ea-8606-3b31d61d899e.png)

### **_buildPhotoView**
![image](https://user-images.githubusercontent.com/16799511/70089202-0d6f0200-15ee-11ea-96c3-a4a5d61b38b0.png)

### **_buildScaleInfo**
![image](https://user-images.githubusercontent.com/16799511/70089671-04326500-15ef-11ea-9818-44d8dc374994.png)

### **_buildResetScaleButton**
![image](https://user-images.githubusercontent.com/16799511/70089697-16140800-15ef-11ea-93a1-726ece893b03.png)

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/16799511/70088731-3e026c00-15ed-11ea-8e78-72ebd587e857.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/16799511/70088686-24f9bb00-15ed-11ea-9518-71e830958e8c.png)

**Is this a *feature* or report a *bug*?**
bug

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
- Flutter 1.9.1+hotfix.6 • channel stable
- photo_view: ^0.9.0
- Windows 10

**Additional context**

**The possible issue could be located in the class** 
**_PhotoViewState**

![image](https://user-images.githubusercontent.com/16799511/70089968-98043100-15ef-11ea-9652-3dbf1818f952.png)

**Comment by renancaraujo** [comment] 2019-12-03 22:57
I will ask you two things: 
The error stack trace and the URL of the image.

Also,[ you can insert code in your issues using markdown](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks). It is easier for bug investigation, 
 readability and _searchability_.

**Comment by lucien144** [comment] 2020-01-09 10:10
I'm experiencing the same issue when setting up a custom scale or calling the `PhotoViewController.reset()`. After some debugging and playing with different version I noticed this bug has been introduced in version 8. Version 7- works fine.

**Comment by GabrielBottari** [comment] 2020-01-18 16:22
I can help a bit here by providing the stack trace:
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      double.* (dart:core-patch/double.dart:38:23)
#2      Matrix4.scale (package:vector_math/src/vector_math_64/matrix4.dart:894:19)
#3      PhotoViewCoreState.build.<anonymous closure> (package:photo_view/src/core/photo_view_core.dart:293:17)
#4      StreamBuilder.build (package:flutter/src/widgets/async.dart:510:74)

After investigation, the scale in photo_view_core line 292 is at some point null.

**Comment by renancaraujo** [comment] 2020-02-15 16:00
Looks like dupe of #217 which was fixed on #254

**Closed by renancaraujo** 2020-02-15 16:00 UTC
Labels: Gallery, bug
