### ISSUE TITLE
[BUG]Image doesn't zoom in after double tap on a physical device, such as iPhone 7

### ISSUE THREAD

**Issue by jims57** [renancaraujo/photo_view#311] opened 2020-08-13 15:09 UTC
In iOS simulator, double tap on an image will be ok to zoom in, but no in a physical device. Is it a bug?

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:photo_view/photo_view.dart';
import 'package:photo_view/photo_view_gallery.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ParentWidget(),
    );
  }
}

class ParentWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => ParentWidgetState();
}

class ParentWidgetState extends State<ParentWidget> {
  List<GalleryItem> galleryItems = [
    GalleryItem(10, 'assets/userImages/largeImage1.jpg'),
    GalleryItem(20, 'assets/userImages/largeImage2.jpg'),
    GalleryItem(30, 'assets/userImages/largeImage3.jpg')
  ];

  int currentImageNo = 2;
  int imageTotalCount = 3;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            GestureDetector(
              child: Text('完成'),
              onTap: () {
                setState(() {
                  currentImageNo = 3;
                });
              },
            ),
            Text('$currentImageNo/$imageTotalCount'),
            Text(
              '更多',
              style: TextStyle(color: Colors.transparent),
            )
          ],
        ),
      ),
      body: Container(
          child: PhotoViewGallery.builder(
        scrollPhysics: const BouncingScrollPhysics(),
        builder: (BuildContext context, int index) {
          return PhotoViewGalleryPageOptions(
            imageProvider: AssetImage(galleryItems[index].image),
            initialScale: PhotoViewComputedScale.contained * 1,
            heroAttributes:
                PhotoViewHeroAttributes(tag: galleryItems[index].id),
          );
        },
        itemCount: galleryItems.length,
        loadingBuilder: (context, event) => Center(
          child: Container(
            child: CircularProgressIndicator(),
          ),
        ),
        enableRotation: false,
        onPageChanged: (newPageIndex) {
          setState(() {
            currentImageNo = newPageIndex + 1;
          });
        },
        backgroundDecoration: BoxDecoration(color: Colors.transparent),
      )),
    );
  }
}

class GalleryItem {
  GalleryItem(id, image) {
    this._id = id;
    this._image = image;
  }

  int _id;

  int get id => _id;

  set id(int value) {
    _id = value;
  }

  String _image;

  String get image => _image;

  set image(String value) {
    _image = value;
  }
}

```

**Comment by renancaraujo** [comment] 2020-08-14 08:37
Dupe of #252.

**Closed by renancaraujo** 2020-08-14 08:37 UTC
Labels: bug
