### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amervelic** [renancaraujo/photo_view#270] opened 2020-04-05 13:13 UTC
loadingBuilder not visible long time on slow network and big picture.

**Comment by renancaraujo** [comment] 2020-04-06 10:46
Can you provide an example that would enable someone to reproduce the bug? 

Since this doesn't follow any issue template nor give any valuable information about the bug, I shall close it for not. If you have anything now that would help reproduce the issue, feel free to reopen it.

**Closed by renancaraujo** 2020-04-06 10:46 UTC
Labels: bug
